site_name: 'Dys:/functional Planet'
site_description: "A place for all things Dys:/functional."
site_author: "Dys:/function Team"
docs_dir: docs/
repo_name: 'dys-function/dys-function.github.io'
repo_url: 'https://github.com/dys-function/dys-function.github.io'
theme:
  icon:
    logo: fontawesome/solid/eye
  favicon: isolation_icon.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
nav:
  - Home: index.md
  - Books: books.md
  - Slices: slices.md
  - Codex: codex.md 
  - Contact: contact.md
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
